StudentManagementSystem/Controllers/StudentRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentManagementSystem.Models;
using StudentManagementSystem.Models.ModelContext;
using StudentManagementSystem.Controllers;

namespace StudentManagementSystem.Controllers
{
    [Authorize]
    public class StudentRegistrationController : Controller
    {
        private UniversityDBContext db = new UniversityDBContext();
        private string CustomDataSaveError = new ErrorController().DataSaveCustomError();

        public StudentRegistrationController()
        {
            ViewBag.title = "Student Registration";
        }


        // GET: StudentRegistration list
        public ActionResult RegList()
        {
            var studentRegistration = db.StudentRegistration.Include(s => s.Student);
            return View(studentRegistration.ToList());
        }

        // GET: StudentRegistration/Details/5
        public ActionResult Details(int? StudentId)
        {
            if (StudentId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentRegistrationModels studentRegistrationModels = db.StudentRegistration.Find(StudentId);
            if (studentRegistrationModels == null)
            {
                return HttpNotFound();
            }
            return View(studentRegistrationModels);
        }

        // GET: StudentRegistration/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Course, "Id", "Title");
            ViewBag.StudentId = new SelectList(db.Student, "Id", "Name");
            return View();
        }

        // POST: StudentRegistration/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentId,CourseId,IsPaymentComplete")] StudentRegistrationModels studentRegistration)
        {
            if (ModelState.IsValid)
            {
                StudentRegistrationModels exitReg = db.StudentRegistration.Find(studentRegistration.StudentId);
                if (exitReg == null)
                {
                    studentRegistration.EnrollDate = DateTime.UtcNow;
                    CourseModels exitCourse = db.Course.Find(studentRegistration.CourseId);
                    var TotalStudent = db.StudentRegistration.Where(c => c.CourseId == studentRegistration.CourseId).Count();
                    if (exitCourse != null)
                    {
                        if (TotalStudent < exitCourse.SeatCount)
                        {
                            try
                            {
                                db.StudentRegistration.Add(studentRegistration);
                                db.SaveChanges();
                                return RedirectToAction("RegList");
                            }
                            catch (Exception ex)
                            {
                                ModelState.AddModelError("customerror", CustomDataSaveError);
                            }
                        }
                        else
                        {
                            ModelState.AddModelError(nameof(studentRegistration.CourseId), "The course set is already full...");
                        }


                    }
                    else
                    {
                        ModelState.AddModelError(nameof(studentRegistration.CourseId), "Select correct course..");
                    }
                }
                else
                {
                    ModelState.AddModelError(nameof(studentRegistration.StudentId), "Student alredy registered");
                }
            }

            ViewBag.CourseId = new SelectList(db.Course, "Id", "Title");
            ViewBag.StudentId = new SelectList(db.Student, "Id", "Name");
            return View(studentRegistration);
        }

        // GET: StudentRegistration/Edit/5
        public ActionResult Edit(int? StudentId)
        {
            if (StudentId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentRegistrationModels studentRegistration = db.StudentRegistration.Find(StudentId);
            if (studentRegistration == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Course, "Id", "Title");
            ViewBag.StudentId = new SelectList(db.Student, "Id", "Name");
            return View(studentRegistration);
        }

        // POST: StudentRegistration/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentId, CourseId,IsPaymentComplete")] StudentRegistrationModels studentRegistration)
        {
            if (ModelState.IsValid)
            {
                StudentRegistrationModels exitReg = db.StudentRegistration.Find(studentRegistration.StudentId);
                if (exitReg != null)
                {
                    studentRegistration.EnrollDate = exitReg.EnrollDate;
                    CourseModels exitCourse = db.Course.Find(studentRegistration.CourseId);
                    var TotalStudent = db.StudentRegistration.Where(c => c.CourseId == studentRegistration.CourseId).Count();
                    if (exitCourse != null)
                    {
                        if (TotalStudent < exitCourse.SeatCount || studentRegistration.CourseId == exitReg.CourseId)
                        {
                            try
                            {
                                db.Entry(exitReg).CurrentValues.SetValues(studentRegistration);
                                db.SaveChanges();
                                return RedirectToAction("RegList");
                            }
                            catch (Exception ex)
                            {
                                ModelState.AddModelError("customerror", CustomDataSaveError);
                            }
                        }
                        else
                        {
                            ModelState.AddModelError(nameof(studentRegistration.CourseId), "The course set is already full...");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(nameof(studentRegistration.CourseId), "Select correct course..");
                    }
                }
                else
                {
                    ModelState.AddModelError(nameof(studentRegistration.StudentId), "Enter correct student");
                }
            }
            ViewBag.CourseId = new SelectList(db.Course, "Id", "Title");
            ViewBag.StudentId = new SelectList(db.Student, "Id", "Name");
            return View(studentRegistration);
        }

        // GET: StudentRegistration/Delete/5
        public ActionResult Delete(int? StudentId)
        {
            if (StudentId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentRegistrationModels studentRegistrationModels = db.StudentRegistration.Find(StudentId);
            if (studentRegistrationModels == null)
            {
                return HttpNotFound();
            }
            return View("Details", studentRegistrationModels);
        }

        // POST: StudentRegistration/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? StudentId)
        {
            if (StudentId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentRegistrationModels studentRegistration = db.StudentRegistration.Find(StudentId);
            if (studentRegistration != null)
            {
                try
                {
                    db.StudentRegistration.Remove(studentRegistration);
                    db.SaveChanges();
                    return RedirectToAction("RegList");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("customerror", CustomDataSaveError);
                }
            }
            return View("Details");
        }

        public ActionResult GetStudent(int? id)
        {
            if (id != null)
            {
                StudentModel student = db.Student.Find(id);
                if (student != null)
                {
                    var data = new { dept = student.Department.DeptName, id = student.DeptId };
                    return Json(data, JsonRequestBehavior.AllowGet);
                }
            }

            return Json(HttpStatusCode.BadRequest);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentManagementSystem/Views/StudentRegistration/Create.cshtml
@model StudentManagementSystem.Models.StudentRegistrationModels

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminShared/_AdminLayout.cshtml";
}

<div class="content">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">@ViewBag.title Form</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post">
            @Html.AntiForgeryToken()
            <div class="card-body">
                <div class="form-group row">
                    @Html.LabelFor(model => model.Student, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.DropDownListFor(model => model.StudentId, (IEnumerable<SelectListItem>)ViewBag.StudentId, "--Select student--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label style="display: none" id="DeparmentLabel" for="DeparmentId" class="col-sm-2 col-form-label">Department</label>
                    <div class="col-sm-10">
                        <input type="hidden" class="form-control" id="DeparmentId" name="Deparment" disabled>
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.Course, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.DropDownListFor(model => model.CourseId, (IEnumerable<SelectListItem>)ViewBag.CourseId, "--Select course--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.IsPaymentComplete, new { @class = "d-none", id = "IsPaymentCompletelabel" })
                    <div class="col-sm-10">
                        @Html.CheckBoxFor(model => model.IsPaymentComplete, new { @class = "d-none" })
                        @Html.ValidationMessageFor(model => model.IsPaymentComplete, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p class='text-center text-danger'>@Html.ValidationMessage("customerror")</p>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-info">Submit</button>
                @Html.ActionLink("Back to List", "RegList", "StudentRegistration", new { @class = "float-right" })
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
</div>



@section adminscripts
{
    <script>
        var student = document.getElementById("StudentId");
        var course = document.getElementById("CourseId");
        var mainUrl = document.location.origin;

        student.addEventListener("change", function () {
            var studentId = student.value;
            if (!!studentId) {
                var url = mainUrl + "/StudentRegistration/GetStudent/" + studentId;
                fetch(url)
                    .then(response => response.json())
                    .then(data => {
                        let dept = document.getElementById("DeparmentId");
                        dept.value = data["dept"];
                        dept.type = "text";
                        document.getElementById("DeparmentLabel").style.display = 'block';
                    });
            }
            else {
                document.getElementById("DeparmentId").type = "hidden";
                document.getElementById("DeparmentLabel").style.display = 'none';
            }
        });

        course.addEventListener("change", function () {
            var courseId = course.value;
            if (!!courseId) {
                document.getElementById("IsPaymentComplete").className = "d-block";
                document.getElementById("IsPaymentCompletelabel").className = "col-sm-2 col-form-label d-block";
            }
            else {
                document.getElementById("IsPaymentComplete").className  = "d-none";
                document.getElementById("IsPaymentCompletelabel").className  = "d-none";
            }
        });
    </script>

    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

StudentManagementSystem/Views/StudentRegistration/Details.cshtml
@model StudentManagementSystem.Models.StudentRegistrationModels

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminShared/_AdminLayout.cshtml";
}

<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">@ViewBag.title Details</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-4 m-auto">
                    <div>
                        <span class="font-weight-bold">
                            @Html.DisplayNameFor(model => model.Student):
                        </span>

                        @Html.DisplayFor(model => model.Student.Name)
                    </div>
                    <p class='text-center text-danger'>@Html.ValidationMessage("customerror")</p>
                </div>
            </div>
            <div class="row">
                <div class="col-4 m-auto">
                    <div>
                        <span class="font-weight-bold">
                            @Html.DisplayNameFor(model => model.Course):
                        </span>

                        @Html.DisplayFor(model => model.Course.Title)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-4 m-auto">
                    <div>
                        <span class="font-weight-bold">
                            @Html.DisplayNameFor(model => model.EnrollDate):
                        </span>

                        @Html.DisplayFor(model => model.EnrollDate)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-4 m-auto">
                    <div>
                        <span class="font-weight-bold">
                            @Html.DisplayNameFor(model => model.IsPaymentComplete):
                        </span>

                        @Html.DisplayFor(model => model.IsPaymentComplete)
                    </div>
                </div>
            </div>
            <div class="row mt-4">
                <p class="col-4 m-auto">
                    @Html.ActionLink("Edit", "Edit", new { StudentId = Model.StudentId }) |
                    @Html.ActionLink("Back to List", "RegList")
                </p>
            </div>
            <div>
                @{
                    if (ViewContext.RouteData.GetRequiredString("action") == "Delete")
                    {
                        <div class="row">
                            <div class="col-md-10 col-md-offset-4">
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()
                                    <br />
                                    <p class="text-danger">*Do you want to delete it!?</p>
                                    <button type="submit" id="createStudentButton" class="btn btn-danger">Delete</button>
                                }
                            </div>
                        </div>

                    }

                }
            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</section>

StudentManagementSystem/Views/StudentRegistration/Edit.cshtml
@model StudentManagementSystem.Models.StudentRegistrationModels

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminShared/_AdminLayout.cshtml";
}

<div class="content">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">@ViewBag.title Form</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post">
            @Html.AntiForgeryToken()
            <div class="card-body">
                <div class="form-group row">
                    @Html.LabelFor(model => model.Student, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        <fieldset disabled>
                            @Html.EditorFor(model => model.Student.Name, new { htmlAttributes = new { @class = "form-control" } })
                        </fieldset>
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.Student.Department, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        <fieldset disabled>
                            @Html.EditorFor(model => model.Student.Department.DeptName, new { htmlAttributes = new { @class = "form-control" } })
                        </fieldset>        
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.Course, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.DropDownListFor(model => model.CourseId, (IEnumerable<SelectListItem>)ViewBag.Course, "--Select course--", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.IsPaymentComplete, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.CheckBoxFor(model => model.IsPaymentComplete)
                        @Html.ValidationMessageFor(model => model.IsPaymentComplete, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <p class='text-center text-danger'>@Html.ValidationMessage("customerror")</p>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-info">Submit</button>
                @Html.ActionLink("Back to List", "RegList", "StudentRegistration", new { @class = "float-right" })
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
</div>



@section adminscripts
{
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

StudentManagementSystem/Views/StudentRegistration/RegList.cshtml
@model IEnumerable<StudentManagementSystem.Models.StudentRegistrationModels>

@{
    ViewBag.Title = ViewBag.title;
    Layout = "~/Views/Shared/AdminShared/_AdminLayout.cshtml";
}

<section class="content">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-6">
                    <h3 class="card-title">@ViewBag.title List</h3>
                </div>
                <div class="col-6 text-right">
                    @Html.ActionLink("Create New", "Create", "StudentRegistration")
                </div>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <div id="jsGrid1" class="jsgrid" style="position: relative; height: 100%; width: 100%;">
                <div class="jsgrid-grid-header jsgrid-header-scrollbar">
                    <table class="jsgrid-table">
                        <tr class="jsgrid-header-row">
                            <th class="jsgrid-header-cell jsgrid-header-sortable" style="width: 150px;">@Html.DisplayNameFor(model => model.Student)</th>
                            <th class="jsgrid-header-cell jsgrid-header-sortable" style="width: 150px;">@Html.DisplayNameFor(model => model.Course)</th>
                            <th class="jsgrid-header-cell jsgrid-header-sortable" style="width: 150px;">@Html.DisplayNameFor(model => model.EnrollDate)</th>
                            <th class="jsgrid-header-cell jsgrid-header-sortable" style="width: 120px;">@Html.DisplayNameFor(model => model.IsPaymentComplete)</th>
                            <th class="jsgrid-header-cell jsgrid-align-right jsgrid-header-sortable" style="width: 100px;">Action</th>
                        </tr>
                    </table>
                </div>

                <div class="jsgrid-grid-body">
                    <table class="jsgrid-table">
                        <tbody>
                            @foreach (var reg in Model)
                            {
                            <tr class="jsgrid-row">

                                <td class="jsgrid-cell" style="width: 150px;">
                                    @Html.DisplayFor(modelItem => reg.Student.Name)
                                </td>
                                <td class="jsgrid-cell" style="width: 150px;">
                                    @Html.DisplayFor(modelItem => reg.Course.Title)
                                </td>
                                <td class="jsgrid-cell" style="width: 150px;">
                                    @Html.DisplayFor(modelItem => reg.EnrollDate)
                                </td>
                                <td class="jsgrid-cell text-center" style="width: 120px;">
                                    @Html.DisplayFor(modelItem => reg.IsPaymentComplete)
                                </td>
                                <td style="width: 100px;">
                                    @Html.ActionLink("Edit", "Edit", new { StudentId = reg.StudentId }) |
                                    @Html.ActionLink("Details", "Details", new { StudentId = reg.StudentId }) |
                                    @Html.ActionLink("Delete", "Delete", new { StudentId = reg.StudentId })
                                </td>

                            </tr>
                            }

                        </tbody>
                    </table>
                </div>
                <div class="jsgrid-pager-container">
                    <div class="jsgrid-pager">
                        Pages: <span class="jsgrid-pager-nav-button jsgrid-pager-nav-inactive-button"><a href="javascript:void(0);">First</a></span>
                        <span class="jsgrid-pager-nav-button jsgrid-pager-nav-inactive-button"><a href="javascript:void(0);">Prev</a></span> <span class="jsgrid-pager-page jsgrid-pager-current-page">1</span>
                        <span class="jsgrid-pager-page"><a href="javascript:void(0);">2</a></span><span class="jsgrid-pager-page"><a href="javascript:void(0);">3</a></span><span class="jsgrid-pager-page"><a href="javascript:void(0);">4</a></span>
                        <span class="jsgrid-pager-page"><a href="javascript:void(0);">5</a></span> <span class="jsgrid-pager-nav-button"><a href="javascript:void(0);">Next</a></span>
                        <span class="jsgrid-pager-nav-button"><a href="javascript:void(0);">Last</a></span> &nbsp;&nbsp; 1 of 5
                    </div>
                </div>
                <div class="jsgrid-load-shader" style="display: none; position: absolute; inset: 0px; z-index: 1000;"></div>
                <div class="jsgrid-load-panel" style="display: none; position: absolute; top: 50%; left: 50%; z-index: 1000;">Please, wait...</div>
            </div>

        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</section>